import Head from "next/head";

import { api } from "~/utils/api";
import LoginPage from "./login";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  // const newD = api.post.create.useMutation()
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const categories = api.category.getCategories
  console.log("🚀 ~ Home ~ categories:", categories)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage/>
    </>
  );
}
