import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import LoginPage from "./login";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  // const newD = api.post.create.useMutation()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage/>
    </>
  );
}
